import mongoose from 'mongoose'

const siteSettingSchema = new mongoose.Schema(
  {
    key: { type: String, required: true, unique: true, default: 'site' },
    siteName: { type: String, default: 'কৃষিকাগজ' },
    tagline: { type: String, default: 'কৃষকের পাশে · মাঠের সত্য খবর' },
    hotline: { type: String, default: '১৬১২৩' },
    notice: { type: String, default: '' },
    logo: { type: String, default: '/logo.png' },
    loginLogo: { type: String, default: '' },
    mobileLogo: { type: String, default: '' },
    favicon: { type: String, default: '/logo.png' },
    faviconRev: { type: String, default: '' },
    defaultNewsImage: { type: String, default: '/placeholder-news.svg' },
    breakingTitle: { type: String, default: 'ব্রেকিং নিউজ' },
    breakingTitleBn: { type: String, default: 'ব্রেকিং নিউজ' },
    breakingTitleEn: { type: String, default: 'Breaking News' },
    newsStoriesTitle: { type: String, default: 'নিউজ স্টোরিজ' },
    newsStoriesTitleBn: { type: String, default: 'নিউজ স্টোরিজ' },
    newsStoriesTitleEn: { type: String, default: 'News Stories' },
    newsStandingTitle: { type: String, default: '' },
    homepageLayout: { type: String, default: 'dynamic' },
    homepageSlots: {
      lead: { type: String, default: '' },
      grid: { type: [String], default: () => Array(9).fill('') },
      mid: { type: [String], default: () => Array(8).fill('') },
      story: { type: String, default: '' },
      storyList: { type: [String], default: () => Array(8).fill('') },
    },
    sectionSlots: { type: mongoose.Schema.Types.Mixed, default: {} },
    sectionSidebars: { type: mongoose.Schema.Types.Mixed, default: {} },
    discussedConfig: { type: mongoose.Schema.Types.Mixed, default: {} },
    latestPopularConfig: {
      type: mongoose.Schema.Types.Mixed,
      default: () => ({
        latestMode: 'auto',
        popularMode: 'auto',
        latestItems: [],
        popularItems: [],
      }),
    },
    lazyBanner: { type: String, default: '' },
    facebookPage: { type: String, default: '' },
    facebookPageId: { type: String, default: '' },
    facebookPageAccessToken: { type: String, default: '' },
    phoneBn: { type: String, default: '' },
    phoneEn: { type: String, default: '' },
    email: { type: String, default: '' },
    addressBn: { type: String, default: '' },
    addressEn: { type: String, default: '' },
    chiefAdvisor: { type: String, default: '' },
    publisher: { type: String, default: '' },
    managingEditor: { type: String, default: '' },
    messageEditor: { type: String, default: '' },
    terms: { type: String, default: '' },
    privacy: { type: String, default: '' },
    aboutUs: { type: String, default: '' },
    liveTvLink: { type: String, default: '' },
    liveTvEmbed: { type: String, default: '' },
    themeColor: { type: String, default: '#03228f' },
    adsEnabled: { type: Boolean, default: true },
    topicGridLimit: { type: Number, default: 8 },
    topicGridSlug: { type: String, default: 'motso' },
    aiWriter: {
      apiKey: { type: String, default: '' },
      model: { type: String, default: 'gpt-4o' },
      temperature: { type: String, default: '0.7' },
      maxTokens: { type: String, default: '500' },
      promptTemplate: { type: String, default: '' },
    },
    namaz: {
      fajr: { type: String, default: '৫:৩০' },
      johor: { type: String, default: '১:৩০' },
      asor: { type: String, default: '৪:০০' },
      magrib: { type: String, default: '৬:০০' },
      esha: { type: String, default: '৭:৩০' },
      jummah: { type: String, default: '১:৪০' },
    },
    social: {
      facebook: { type: String, default: '' },
      twitter: { type: String, default: '' },
      instagram: { type: String, default: '' },
      linkedin: { type: String, default: '' },
      youtube: { type: String, default: '' },
    },
    seo: {
      metaTitle: { type: String, default: '' },
      metaKeyword: { type: String, default: '' },
      metaDescription: { type: String, default: '' },
      metaAuthor: { type: String, default: '' },
      googleAnalytics: { type: String, default: '' },
      alexaAnalytics: { type: String, default: '' },
      googleVerification: { type: String, default: '' },
      ogImage: { type: String, default: '' },
      horizontal1: { type: String, default: '' },
      horizontal2: { type: String, default: '' },
      horizontal3: { type: String, default: '' },
      horizontal4: { type: String, default: '' },
      horizontal5: { type: String, default: '' },
      horizontalBig1: { type: String, default: '' },
      horizontalBig2: { type: String, default: '' },
      horizontalBig3: { type: String, default: '' },
      horizontalBig4: { type: String, default: '' },
      vertical: { type: String, default: '' },
      bottomPopup: { type: String, default: '' },
    },
  },
  { timestamps: true },
)

export default mongoose.model('SiteSetting', siteSettingSchema)
